# Generated by Django 6.0.6 on 2026-06-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=32)),
                ('brand', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_vehicles', to='terminal.terminal')),
            ],
            options={
                'unique_together': {('terminal', 'registration_number')},
            },
        ),
        migrations.CreateModel(
            name='GateCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macroscop_channel_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('entry', 'Въезд'), ('exit', 'Выезд')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_cameras', to='terminal.terminal')),
            ],
            options={
                'unique_together': {('terminal', 'macroscop_channel_id')},
            },
        ),
        migrations.CreateModel(
            name='MacroscopIntegrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_archive_poll_at', models.DateTimeField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macroscop_state', to='terminal.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('entry', 'Въезд'), ('exit', 'Выезд')], max_length=16)),
                ('passed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('macroscop', 'Macroscop'), ('manual', 'Вручную')], max_length=16)),
                ('reliability', models.FloatField(blank=True, null=True)),
                ('recognized_brand', models.CharField(blank=True, default='', max_length=128)),
                ('recognized_color', models.CharField(blank=True, default='', max_length=64)),
                ('recognized_type', models.CharField(blank=True, default='', max_length=64)),
                ('macroscop_event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('raw_event', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fleet_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='vehicle_fleet.fleetvehicle')),
                ('gate_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_passes', to='vehicle_fleet.gatecamera')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_gate_passes', to='terminal.terminal')),
            ],
            options={
                'ordering': ['-passed_at'],
            },
        ),
    ]
