# Generated by Django 6.0.6 on 2026-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclegatepass',
            name='source',
            field=models.CharField(choices=[('macroscop', 'Macroscop'), ('dahua', 'Dahua'), ('manual', 'Вручную')], max_length=16),
        ),
    ]
