"""
Django settings for macroscope project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--)=uhg5qt5qf3f2#cctde4j=6w&1*63=xazdu_gedmlboquygb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'terminal',
    'vehicle_fleet',
    'vehicle_fleet_integration',
]

SPECTACULAR_SETTINGS = {
    'TITLE': 'Vehicle Gate Pass API',
    'DESCRIPTION': 'Журнал въездов/выездов транспортных средств (T-068)',
    'VERSION': '1.0.0',
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'macroscope.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'macroscope.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Macroscop ANPR integration (T-068)
# Учётные данные не хранить в репозитории — задавать через .env.

MACROSCOP_INTEGRATION = {
    'ENABLED': env.bool('MACROSCOP_ENABLED', default=False),
    'BASE_URL': env('MACROSCOP_BASE_URL', default='http://10.66.66.21:8080'),
    'LOGIN': env('MACROSCOP_LOGIN', default='User'),
    'PASSWORD_MD5': env('MACROSCOP_PASSWORD_MD5', default=''),
    'TERMINAL_ID': env.int('MACROSCOP_TERMINAL_ID', default=None),
    'TERMINAL_TIMEZONE': env('MACROSCOP_TERMINAL_TIMEZONE', default='Europe/Moscow'),
    'MIN_RELIABILITY': env.float('MACROSCOP_MIN_RELIABILITY', default=0.85),
    'DEDUP_WINDOW_SEC': env.int('MACROSCOP_DEDUP_WINDOW_SEC', default=60),
    'ARCHIVE_POLL_INTERVAL_SEC': env.int('MACROSCOP_ARCHIVE_POLL_INTERVAL_SEC', default=300),
    'REQUEST_TIMEOUT_SEC': env.int('MACROSCOP_REQUEST_TIMEOUT', default=30),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'ts': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'ts',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'vehicle_fleet_integration': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

DAHUA_INTEGRATION = {
    'BASE_URL': env('DAHUA_BASE_URL', default='http://195.19.150.181:8000'),
    'LOGIN': env('DAHUA_LOGIN', default='admin'),
    'PASSWORD': env('DAHUA_PASSWORD', default=''),
    'TIMEZONE': env('DAHUA_TIMEZONE', default='Europe/Moscow'),
    'REQUEST_TIMEOUT_SEC': env.int('DAHUA_REQUEST_TIMEOUT', default=30),
    # Dahua Confidence 0–100 → делим на 100; у Macroscop шкала та же, но алгоритмы разные
    'MIN_RELIABILITY': env.float('DAHUA_MIN_RELIABILITY', default=0.60),
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
